### ISSUE TITLE
Was this project left in any state of usability?

### ISSUE THREAD

**Issue by InevitablyDivinity** [PazerOP/TF2Vulkan#3]
Does it render anything? Is the game left playable? Or was it left so early in development that progress hadn't gotten that far?

**Comment by PazerOP** [comment]
UI/models/brushes work, but only diffuse is supported. The shaders are enormously complex and converting them would have been a monumental task in and of itself, so I stopped work shortly after getting to this point:

![image](https://user-images.githubusercontent.com/6569500/108823351-25c19880-7575-11eb-9013-064157db2c5b.png)

**Comment by InevitablyDivinity** [comment]
This is still incredible in itself. Good work. I think I have some fairly substantial plans to make use of what you've started (assuming you're still alright with that, which the license seems to imply). Though unfortunately it would be going towards a closed-source project.

**Comment by PazerOP** [comment]
Go nuts 👍
